test: off
before_build:
  - nuget restore
  - touch ow.Framework.Tests/appsettings.json
  - touch ow.Service.District/appsettings.json
  - touch ow.Service.Gate/appsettings.json
  - touch ow.Service.Login/appsettings.json
  - touch ow.Utils.GenerateItemsForView/appsettings.json
